# Seeds Firestore with the sample café content, from outside the app.
#
#   $env:HL_ADMIN_EMAIL='...'; $env:HL_ADMIN_PASSWORD='...'
#   powershell -ExecutionPolicy Bypass -File tool\seed_firestore.ps1
#   powershell -ExecutionPolicy Bypass -File tool\seed_firestore.ps1 -Check
#
# ## Why this exists when the admin panel has a "Seed sample data" button
#
# Two reasons, and one admission.
#
# The real reason is verification. The button needs the app running, signed in as
# admin, and an emulator or a device; the emulator on this machine has no hardware
# acceleration. Running the seed from here means the one-time write can be proved
# against the live rules *now*, before anyone depends on it. Getting it wrong is
# cheap from here and expensive from a phone: the seed is an atomic batch, so a
# single refused document leaves nothing written and the panel still looks empty.
#
# The admission: this does the same work as the button, by a different route. If
# the two ever disagree it is because this replays `tool/seed_documents.json`
# rather than calling the app's serialiser — so that file is generated by the real
# `toMap` extensions (`tool/dump_seed_documents.dart`) rather than hand-written.
# Regenerate it after touching a model:
#
#   flutter test tool/dump_seed_documents.dart
#
# ## What it will not do
#
# It refuses if any order exists. Seeding is a first-run convenience, and a second
# run must not be able to bury real trading history under mock data. The button in
# the admin panel has the same guard, for the same reason.
param(
  [string]$ProjectId = "",
  [string]$Database = "(default)",
  [switch]$Check,
  [switch]$Force
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot

# --- configuration ------------------------------------------------------------

$gsp = Join-Path $repoRoot "android\app\google-services.json"
if (-not (Test-Path $gsp)) { throw "google-services.json not found at $gsp." }
$gspJson = Get-Content $gsp -Raw | ConvertFrom-Json
if (-not $ProjectId) { $ProjectId = $gspJson.project_info.project_id }
$apiKey = $gspJson.client[0].api_key[0].current_key

$docsPath = Join-Path $PSScriptRoot "seed_documents.json"
if (-not (Test-Path $docsPath)) {
  throw "seed_documents.json is missing. Run:`n  flutter test tool/dump_seed_documents.dart"
}

$docs = Get-Content $docsPath -Raw | ConvertFrom-Json
$names = @($docs.PSObject.Properties.Name)

Write-Host "project:  $ProjectId" -ForegroundColor DarkGray
Write-Host "database: $Database" -ForegroundColor DarkGray
Write-Host "documents: $($names.Count)" -ForegroundColor DarkGray

# --- existing orders guard ----------------------------------------------------

function SignIn([string]$email, [string]$password) {
  $body = @{ email = $email; password = $password; returnSecureToken = $true } | ConvertTo-Json
  return (Invoke-RestMethod `
    -Uri "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=$apiKey" `
    -Method Post -Body $body -ContentType "application/json").idToken
}

$adminEmail = $env:HL_ADMIN_EMAIL
$adminPassword = $env:HL_ADMIN_PASSWORD
if (-not $adminEmail -or -not $adminPassword) {
  throw "Set the admin credentials with:`n  `$env:HL_ADMIN_EMAIL='...'`n  `$env:HL_ADMIN_PASSWORD='...'"
}

$token = SignIn $adminEmail $adminPassword
$headers = @{ Authorization = "Bearer $token" }

# `limit: 1` — enough to know whether any exist, and a deliberate choice: this
# returns the only count that matters, without waiting on a collection that could
# grow to tens of thousands of orders.
$countQuery = @{
  structuredQuery = @{
    from = @(@{ collectionId = "orders" })
    limit = 1
  }
} | ConvertTo-Json -Depth 8

# Counting `runQuery` results in PowerShell has two traps, both of which produced
# confidently wrong numbers before this helper existed.
#
#   * `runQuery` always emits at least one response, even for an empty collection —
#     one carrying just a `readTime`. So responses != documents.
#   * Wrapping the call in `@( ... )` to force an array *wraps the array*: you get
#     a one-element array whose single element is the 54-element result, and
#     `.Count` reports 1. This is silent. Every collection in this project "had
#     exactly one document" for as long as this was written that way.
#
# `Measure-Object` enumerates, so it counts documents, and 0 for an empty
# collection.
function Count-Documents([string]$collection, [string]$whereCustomerUid = "") {
  $structured = @{ from = @(@{ collectionId = $collection }) }

  if ($whereCustomerUid) {
    $structured.where = @{
      fieldFilter = @{
        field = @{ fieldPath = "customerUid" }
        op = "EQUAL"
        value = @{ stringValue = $whereCustomerUid }
      }
    }
  }

  $query = @{ structuredQuery = $structured } | ConvertTo-Json -Depth 10
  $result = Invoke-RestMethod `
    -Uri "https://firestore.googleapis.com/v1/projects/$ProjectId/databases/$Database/documents:runQuery" `
    -Headers $headers -Method Post -Body $query -ContentType "application/json"

  return ($result | Measure-Object).Count
}

$existingOrders = Count-Documents "orders"

# -Check before the guard, not after. A report mode that throws when there is
# something to report is useless: the one time you want to see what is already in
# the database is to decide whether to overwrite it, which is exactly when the
# guard fires. So -Check reports and exits without writing, and says what a real
# run would do.
if ($Check) {
  Write-Host ""
  Write-Host "no documents written (-Check)" -ForegroundColor Cyan
  foreach ($coll in @("menuItems", "menuCategories", "promos", "staffMembers", "orders")) {
    Write-Host ("  {0,-16} {1}" -f $coll, (Count-Documents $coll))
  }

  Write-Host ""
  if ($existingOrders -gt 0 -and -not $Force) {
    Write-Host "a real run would REFUSE: $existingOrders orders already exist." -ForegroundColor Yellow
    Write-Host "Seeding would bury them under 54 mock orders." -ForegroundColor Yellow
    exit 1
  }

  Write-Host "a real run would write $($names.Count) documents." -ForegroundColor Green
  exit 0
}

if ($existingOrders -gt 0 -and -not $Force) {
  throw @"
The orders collection is not empty ($existingOrders documents).

Seeding writes 54 mock orders alongside the menu, staff and settings. With real
orders already present that would bury them under invented history that looks
identical, and there is no way to tell the two apart in the panel afterwards.

Run with -Check first to see what is there. Delete the mock data yourself once you
have real orders, or pass -Force if you are sure.
"@
}

# --- typed values -------------------------------------------------------------
#
# The REST API takes `{ "stringValue": "x" }`, not `"x"`. Converting here rather
# than at each call site, because getting it subtly wrong looks like a rules
# failure rather than a serialisation one.

function ToFirestoreValue($value) {
  if ($null -eq $value) { return @{ nullValue = $null } }
  if ($value -is [bool]) { return @{ booleanValue = $value } }
  if ($value -is [int] -or $value -is [long] -or $value -is [double] -or $value -is [decimal]) {
    return @{ doubleValue = $value }
  }

  # String before IEnumerable. A PowerShell string *is* IEnumerable, so the array
  # branch below would happily iterate "Kopi" into five characters and then
  # recurse on each one — which recurses on the single-character string, which
  # iterates into one character, forever. The failure surfaces as a call depth
  # overflow with nothing in the message pointing at a string.
  if ($value -is [string]) { return @{ stringValue = $value } }

  if ($value -is [PSCustomObject]) {
    $fields = @{}
    foreach ($p in $value.PSObject.Properties) { $fields[$p.Name] = ToFirestoreValue $p.Value }
    return @{ mapValue = @{ fields = $fields } }
  }

  if ($value -is [System.Collections.IDictionary]) {
    $fields = @{}
    foreach ($key in $value.Keys) { $fields[$key] = ToFirestoreValue $value[$key] }
    return @{ mapValue = @{ fields = $fields } }
  }

  if ($value -is [System.Collections.IEnumerable]) {
    return @{ arrayValue = @{ values = @($value | ForEach-Object { ToFirestoreValue $_ }) } }
  }

  return @{ stringValue = [string]$value }
}

function DocName([string]$path) {
  return "projects/$ProjectId/databases/$Database/documents/$path"
}

# --- write --------------------------------------------------------------------

Write-Host ""
Write-Host "writing..." -ForegroundColor Cyan

$writes = @()
foreach ($name in $names) {
  $fields = @{}
  foreach ($p in $docs.$name.PSObject.Properties) {
    $fields[$p.Name] = ToFirestoreValue $p.Value
  }
  $writes += @{
    update = @{ name = (DocName $name); fields = $fields }
    updateMask = @{ fieldPaths = @($fields.Keys) }
  }
}

# Committed in one batch, matching the app's `WriteBatch`. Two reasons that is the
# right shape here: it is the same atomicity the button has, so a refused document
# fails the whole thing rather than leaving a half-seeded shop; and 88 documents in
# 88 round trips is slow enough to be worth avoiding.
$body = @{ writes = $writes } | ConvertTo-Json -Depth 20

Invoke-RestMethod `
  -Uri "https://firestore.googleapis.com/v1/projects/$ProjectId/databases/$Database/documents:commit" `
  -Headers $headers -Method Post -Body $body -ContentType "application/json" | Out-Null

Write-Host "  committed $($writes.Count) documents" -ForegroundColor Green

# --- verify by reading back ---------------------------------------------------
#
# A successful commit says the rules allowed the write. It does not say the app
# can read it back, and those are different documents in different rules: the menu
# is world-readable, orders are admin-only, and a shape error surfaces only on the
# read path, as a silently empty list rather than an error.

Write-Host ""
Write-Host "reading back as the admin would" -ForegroundColor Cyan

foreach ($coll in @("menuItems", "menuCategories", "promos", "staffMembers", "orders")) {
  Write-Host ("  {0,-16} {1}" -f $coll, (Count-Documents $coll))
}

# The settings document is what carries isOpen and the fee tiers. If it is missing,
# the customer app falls back to "open" — the safe default, but silently wrong
# about delivery pricing, so it is worth asserting rather than assuming.
# A plain GET on a missing document returns 404 and, in a try/catch, a variable
# that was never assigned. Both cases mean "absent", and both mean the customer
# app silently falls back to `isOpen: true` and placeholder fees — so this is
# worth asserting rather than reporting optimistically. The earlier version read
# `.exists` off a failed GET and printed a spurious warning about a document it
# had in fact just written.
$settings = $null
try {
  $settings = Invoke-RestMethod `
    -Uri "https://firestore.googleapis.com/v1/$(DocName 'settings/highlanders')" `
    -Headers $headers -Method Get
} catch {
  $settings = $null
}

Write-Host ""
if ($null -eq $settings) {
  Write-Host "WARNING: settings/highlanders is not readable as admin." -ForegroundColor Yellow
  Write-Host "         The customer app will quote placeholder delivery fees." -ForegroundColor Yellow
} else {
  Write-Host ("settings/highlanders: isOpen={0}  baseFee={1}  freeOver={2}" -f `
    $settings.fields.isOpen.booleanValue,
    $settings.fields.baseFee.doubleValue,
    $settings.fields.freeOver.doubleValue) -ForegroundColor DarkGray
}

Write-Host ""
Write-Host "seeded" -ForegroundColor Green
Write-Host ""
Write-Host "This is invented data. Menu, prices, photos, staff, the barangay list," -ForegroundColor Yellow
Write-Host "the cafe address and the fee rates all need replacing with the real thing." -ForegroundColor Yellow
exit 0
