/// Firestore collection and document naming.
///
/// Every path in the app goes through this file. The reason is not tidiness:
/// the security rules in `firestore.rules` name the same collections, and a
/// typo in a collection name does not fail loudly — it writes to an orphan
/// collection that no rule governs, and the catch-all at the bottom of the rules
/// denies reads on it. The document disappears rather than erroring.
///
/// The catch-all is the reason the tests in `firestore_rules_test.dart` probe an
/// undeclared collection and expect a 403.
class FirestorePaths {
  const FirestorePaths._();

  /// Menu items. Readable by anyone, written by admins.
  static const String menuItems = 'menuItems';

  /// Menu categories ("Coffee", "Brews"). Readable by anyone.
  static const String menuCategories = 'menuCategories';

  /// Promotional banners. Readable by anyone.
  static const String promos = 'promos';

  /// Shop configuration. A single well-known document rather than a collection
  /// of versions — see [settingsDoc].
  static const String settings = 'settings';

  /// Orders from customers. The only collection with per-customer rules.
  static const String orders = 'orders';

  /// Staff roster: baristas, riders, managers.
  static const String staffMembers = 'staffMembers';

  /// Saved delivery addresses. Keyed by uid.
  static const String addresses = 'addresses';

  /// The one shop-settings document id.
  ///
  /// A single id means the app reads one document instead of running a
  /// `where('shopId', ==)` query for a shop that will never be more than one
  /// shop. Public read is allowed on `settings`, so a signed-out customer still
  /// sees the correct opening hours.
  static const String settingsDoc = 'highlanders';

  /// Address document ids are user-scoped, so two customers cannot collide on
  /// the same autogenerated id.
  static String addressDoc(String uid, String addressId) => '${uid}_$addressId';

  /// Staff document ids are the staff member's own slug.
  static String staffDoc(String staffId) => staffId;
}